let baby = "Baby shark, ";
let shark = " doo doo doo doo doo doo doo";
console.log(baby + shark);
console.log(baby + shark);
console.log(baby + shark);
console.log(baby);
let mom = "Mommy shark, ";
console.log(mom + shark);
console.log(mom + shark);
console.log(mom + shark);
console.log(mom);
let dad = "Daddy shark, ";
console.log(dad + shark);
console.log(dad + shark);
console.log(dad + shark);
console.log(dad);
let grand = "Grandma shark, ";
console.log(grand + shark);
console.log(grand + shark);
console.log(grand + shark);
console.log(grand);
let granda = "Grandpa shark, ";
console.log(granda + shark);
console.log(granda + shark);
console.log(granda + shark);
console.log(granda);
